import Head from 'next/head'
<<<<<<< HEAD
import { Stack } from '@chakra-ui/react'
import dynamic from 'next/dynamic'
import Header from '../components/header'
import { useState } from 'react'
import About from '../components/about'
import Contact from '../components/contact'
=======
import { Grid, GridItem, Stack, Flex, Link, Center } from '@chakra-ui/react'
import dynamic from 'next/dynamic'
import Header from '../components/header'
import { useState } from 'react'
import Project from '../components/project'
import About from '../components/about'
import Contact from '../components/contact'
import { data } from '../utils'
>>>>>>> d93eb95968445dc1583cbae8225ebf9c3bdc4724
import Footer from './footer'

const Model = dynamic(
  () => import('../components/model.js'),
  { ssr: false }
)

export default function Mobile () {
<<<<<<< HEAD
  const [blur, toggleBlur] = useState(false)
=======

  const [blur, toggleBlur] = useState(false)
  const [showProject, toggleShowProject] = useState(false)
  const [project, setProject] = useState()
>>>>>>> d93eb95968445dc1583cbae8225ebf9c3bdc4724

  return (
    <>
      <Head>
        <title>Kimberly Nguyen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<<<<<<< HEAD
      <Stack w="100vw" zIndex="5" position="absolute" bottom={0} filter={blur && "auto"} blur={blur && "6px"} opacity={blur && 0.25} p={6}>
        <Header blur={blur} toggleBlur={toggleBlur} />
      </Stack>
=======
        <Stack w="100vw" zIndex="5" position="absolute" bottom={0} filter={blur && "auto"} blur={blur && "6px"} opacity={blur && 0.25} p={6}>
          <Header blur={blur} toggleBlur={toggleBlur} />
        </Stack>

>>>>>>> d93eb95968445dc1583cbae8225ebf9c3bdc4724
      {blur &&
        <>
          <Stack zIndex="10" position="fixed">
            <Footer /> 
          </Stack>
          <Stack spacing={8} p={6} h="100vh" w="100vw" overflow="scroll" position="absolute" zIndex="7" onClick={() => toggleBlur(false)} cursor="grab">
            <Contact />
            <About />
          </Stack>
        </>
      }
      <Stack h="100vh" w="100vw" filter={blur && "auto"} blur={blur && "6px"} opacity={blur && 0.5}>
        <Model />
      </Stack>
    </>
  )
}
