import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Container, Grid, GridItem, Stack, Flex, Image, VStack, Heading, Text, Tag, HStack, Button, Link, Wrap, useDisclosure, Modal, ModalOverlay, ModalHeader, ModalCloseButton, ModalBody, Lorem, ModalFooter, ModalContent, Box, Center, useMediaQuery } from '@chakra-ui/react'
import dynamic from 'next/dynamic'
import Header from '../components/header'
import { useState } from 'react'
import Project from '../components/project'
import About from '../components/about'
import Contact from '../components/contact'
import { ST } from 'next/dist/shared/lib/utils'
import Mobile from '../components/mobile'
import Desktop from '../components/desktop'

export default function Home() {

  const [isSmallerThan400] = useMediaQuery('(max-width: 400px)')

  return (
    <>
      <Head>
        <title>Kimberly Nguyen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isSmallerThan400 ? <Mobile /> : <Desktop />}
    </>
  )
}
