import Head from 'next/head'
import { useMediaQuery } from '@chakra-ui/react'
import Mobile from '../components/mobile'
import Desktop from '../components/desktop'

export default function Home() {
  const [isSmallerThan400] = useMediaQuery('(max-width: 400px)')

  return (
    <>
      <Head>
        <title>Kimberly Nguyen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isSmallerThan400 ? <Mobile /> : <Desktop />}
    </>
  )
}
