import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Container, Grid, GridItem, Stack, Flex, Image, VStack, Heading, Text, Tag, HStack, Button, Link, Wrap } from '@chakra-ui/react'
import dynamic from 'next/dynamic'
import Header from '../components/header'
import ChakraCarousel from '../components/carousel'

const inter = Inter({ subsets: ['latin'] })

const Model = dynamic(
  () => import('../components/Model'),
  { ssr: false }
)

const data = [
  {
    userId: 1,
    id: 1,
    title: "one",
    body: "one body",
    src: "/opossum.jpg"
  },
  {
    userId: 2,
    id: 2,
    title: "two",
    body: "two body",
    src: "/joshuatree.jpg"
  },
  {
    userId: 3,
    id: 3,
    title: "three",
    body: "three body",
    src: "/joshuatree.jpg"
  },
  {
    userId: 3,
    id: 3,
    title: "three",
    body: "three body",
    src: "/joshuatree.jpg"
  },
  {
    userId: 3,
    id: 3,
    title: "three",
    body: "three body",
    src: "/joshuatree.jpg"
  },
  {
    userId: 3,
    id: 3,
    title: "three",
    body: "three body",
    src: "/joshuatree.jpg"
  },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Kimberly Nguyen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack h="100vh" w="100vw" zIndex="5" position="absolute">
        <Grid
          height="100%"
          templateRows='1fr auto'
          templateColumns='repeat(4, 1fr)'
          bg="transparent"
        >
          <GridItem
          rowSpan={1}
          colSpan={4}
          bg="red"
          height="100%"
          >
            <ChakraCarousel>
              {data.map((child, index) => {
                return <Image key={index} alt={index} src={child.src} />
              })}
            </ChakraCarousel>
          </GridItem>
          <GridItem
            rowSpan={1}
            colSpan={1}
            p={8}
          >
            <Header />
          </GridItem>
          <GridItem
            rowSpan={1}
            colStart={3}
            colEnd={4}
            p={8}
          >
            <Flex
              direction="column"
            >
              <Link><h1>Next Music</h1></Link>
            </Flex>
          </GridItem>
          <GridItem
            rowSpan={1}
            colStart={4}
            colEnd={5}
            p={8}
          >
            <p>mapc.github.io/digital-equity-report

2022

Designed and developed a digital toolkit alongside Metropolitan Area Planning Council&apos;s civic technologists and data analysts to share resources and inform decisions around municipal broadband access. The plan includes over 30 interactive data visualizations created using Tableau and Mapbox. The site itself was built and deployed using React and Gatsby.</p>
          </GridItem>
        </Grid>
      </Stack>

      <Stack h="100vh" w="100vw">
        <Model />
      </Stack>

    </>
  )
}
